hotfix/submission-pagination
TACC/Core-CMS-Custom pull request #129
Opened 2023-03-09 20:58 UTC by shayanaijaz

## Overview

The goal for this was to improve load times for the admin submissions page and implement pagination is the user submissions page

## Related

## Changes

1 - Created a new query that retrieves all the submissions and logs as an aggregate and bundles it all into a nice json object that the view expects. This eliminates the need to manually select and assign each field (e.g id = submission[0]) and also hopefully improves load times since we are only doing one query now to retrieve all the data.

2 - When updating the response in `admin_submissions/views.py` I added an `offset` and `limit` functionality. With this it only does the processing on the records that will be displayed on the page and ignores any records that will not be. This should also help in boosting performance.

2 - Added pagination to the user submission page

## Testing

1. In order to mock some data for local testing make changes to the following files

`apcd_cms/src/apps/admin_submissions/views.py:`

<details>
       <summary>View Snippet</summary>

 Replace line 25 with the following:

  ```js
submission_content =[
        ({
            'submission_id': 1,
            'apcd_id': 1,
            'submitter_id': 1,
            'file_name': 'T_GLDNRLE_10000000_202303_202303.zip',
            'status': 'complete',
            'outcome': 'failed',
            'received_timestamp': '2022-09-27T15:25:24.285442',
            'updated_at': '2022-09-27T15:25:24.285442',
            'org_name': 'chcd',
            'view_modal_content': [
                {
                    'log_id': 3, 
                    'submission_id': 1, 
                    'file_type': 'ME', 
                    'validation_suite': 'eligibility_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Member Eligibility'
                }, 
                {
                    'log_id': 5, 
                    'submission_id': 1, 
                    'file_type': 'PV', 
                    'validation_suite': 'provider_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Provider'
                }
            ]
        }),
        ({
            'submission_id': 2,
            'apcd_id': 1,
            'submitter_id': 1,
            'file_name': 'T_GLDNRLE_10000000_202303_202303.zip',
            'status': 'complete',
            'outcome': 'failed',
            'received_timestamp': '2022-09-27T15:25:24.285442',
            'updated_at': '2022-09-27T15:25:24.285442',
            'org_name': 'chcd',
            'view_modal_content': [
                {
                    'log_id': 3, 
                    'submission_id': 1, 
                    'file_type': 'ME', 
                    'validation_suite': 'eligibility_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Member Eligibility'
                }
            ]
        }),
        ({
            'submission_id': 3,
            'apcd_id': 1,
            'submitter_id': 1,
            'file_name': 'T_GLDNRLE_10000000_202303_202303.zip',
            'status': 'complete',
            'outcome': 'failed',
            'received_timestamp': '2022-09-27T15:25:24.285442',
            'updated_at': '2022-09-27T15:25:24.285442',
            'org_name': 'chcd',
            'view_modal_content': [
                {
                    'log_id': 5, 
                    'submission_id': 1, 
                    'file_type': 'PV', 
                    'validation_suite': 'provider_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Provider'
                }
            ]
        }),
        ({
            'submission_id': 4,
            'apcd_id': 1,
            'submitter_id': 1,
            'file_name': 'T_GLDNRLE_10000000_202303_202303.zip',
            'status': 'complete',
            'outcome': 'failed',
            'received_timestamp': '2022-09-27T15:25:24.285442',
            'updated_at': '2022-09-27T15:25:24.285442',
            'org_name': 'chcd',
            'view_modal_content': [
                {
                    'log_id': 2, 
                    'submission_id': 1, 
                    'file_type': '  ', 
                    'validation_suite': 'spark_medical_suite', 
                    'outcome': 'failed', 
                    'file_type_name': None
                }, 
                {
                    'log_id': 5, 
                    'submission_id': 1, 
                    'file_type': 'PV', 
                    'validation_suite': 'provider_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Provider'
                }
            ]
        }),
        ({
            'submission_id': 5,
            'apcd_id': 1,
            'submitter_id': 1,
            'file_name': 'T_GLDNRLE_10000000_202303_202303.zip',
            'status': 'complete',
            'outcome': 'failed',
            'received_timestamp': '2022-09-27T15:25:24.285442',
            'updated_at': '2022-09-27T15:25:24.285442',
            'org_name': 'chcd',
            'view_modal_content': [
                {
                    'log_id': 3, 
                    'submission_id': 1, 
                    'file_type': 'ME', 
                    'validation_suite': 'eligibility_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Member Eligibility'
                }, 
                {
                    'log_id': 5, 
                    'submission_id': 1, 
                    'file_type': 'PV', 
                    'validation_suite': 'provider_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Provider'
                }
            ]
        }),
        ({
            'submission_id': 6,
            'apcd_id': 1,
            'submitter_id': 1,
            'file_name': 'T_GLDNRLE_10000000_202303_202303.zip',
            'status': 'complete',
            'outcome': 'failed',
            'received_timestamp': '2022-09-27T15:25:24.285442',
            'updated_at': '2022-09-27T15:25:24.285442',
            'org_name': 'chcd',
            'view_modal_content': [
                {
                    'log_id': 3, 
                    'submission_id': 1, 
                    'file_type': 'ME', 
                    'validation_suite': 'eligibility_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Member Eligibility'
                }, 
                {
                    'log_id': 4, 
                    'submission_id': 1, 
                    'file_type': 'PC', 
                    'validation_suite': 'pharmacy_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Pharmacy Claims'
                }
            ]
        }),
        ({
            'submission_id': 7,
            'apcd_id': 1,
            'submitter_id': 1,
            'file_name': 'T_GLDNRLE_10000000_202303_202303.zip',
            'status': 'complete',
            'outcome': 'failed',
            'received_timestamp': '2022-09-27T15:25:24.285442',
            'updated_at': '2022-09-27T15:25:24.285442',
            'org_name': 'chcd',
            'view_modal_content': [
                {
                    'log_id': 3, 
                    'submission_id': 1, 
                    'file_type': 'ME', 
                    'validation_suite': 'eligibility_suite', 
                    'outcome': 'failed', 
                    'file_type_name': 'Member Eligibility'
                }
            ]
        }),
        ({
            'submission_id': 8,
            'apcd_id': 1,
            'submitter_id': 1,
            'file_name': 'T_GLDNRLE_10000000_202303_202303.zip',
            'status': 'complete',
            'outcome': 'failed',
            'received_timestamp': '2022-09-27T15:25:24.285442',
            'updated_at': '2022-09-27T15:25:24.285442',
            'org_name' [...]

2023-03-09 22:18 UTC, fnets approved these changes
This LGTM, and it works locally for me. I ran the query in the PPRD VM, and it comes back pretty quick! Good job.

2023-03-09 22:21 UTC, edmondsgarrett approved these changes
Everything looks normal, LGTM!

2023-03-13 19:39 UTC, fnets requested changes

2023-03-13 19:39 UTC, fnets commented on apcd-cms/src/apps/utils/apcd_database.py
> +        results = [row[0] for row in cur.fetchall()]
I think it would be more performant to make this a `cursor.fetchone()` call, or even `fetchmany`, since we're only using the first row.

2023-03-13 19:39 UTC, fnets commented on apcd-cms/src/apps/admin_submissions/views.py
> +            'received_timestamp': parser.parse(s['received_timestamp']),
Has this parse statement been tested with our DB? I noticed that you're not setting a parse object.

2023-03-14 16:06 UTC, sophia-massie approved these changes
LGTM Ran the query on the VM and it was very quick. Thank you!

2023-03-15 15:53 UTC, fnets approved these changes

2023-03-15 16:23 UTC, merged