bug/FP-1977: Remove scroll wheels from numeric input fields
TACC/Core-CMS-Custom pull request #135
Opened 2023-03-21 18:41 UTC by edmondsgarrett

## Overview
…

## Related

- [FP-1977](https://jira.tacc.utexas.edu/browse/FP-1977)
…

## Changes
- Added CSS for `input` to hide scroll arrows from browser
…

## Testing

1. Navigate to http://localhost:8000/register/request-to-submit/
2. Fill out all required fields prior to entity 'coverage estimates'
3. On each coverage estimate field, check that:
   - There are no arrows on the right side of the field
   - Step size is still enforced on the input (whole integers for the first two fields, step of 0.01 for last field)
4. Ensure form can be submitted successfully after all input validation met

## UI
Before:
![17294E13-9417-4BFE-AD97-A04F4B8B3C60_1_102_o](https://user-images.githubusercontent.com/43251554/226709413-ebcc637b-76e4-4061-8a53-23fbc5277f51.jpeg)

After:
![6DC720EB-C525-458A-88FF-E3EC29F90F88_1_102_o](https://user-images.githubusercontent.com/43251554/226709462-335250c0-84e6-4090-821e-3fc1f1607550.jpeg)

…

2023-03-21 21:04 UTC, fnets requested changes
Feel free to ignore, but I think there's just a little extraneous code in the CSS.

2023-03-21 21:04 UTC, fnets commented on apcd-cms/src/apps/registrations/static/registrations/css/submission_form.css
> +input::-webkit-outer-spin-button,
```suggestion
```

2023-03-21 21:04 UTC, fnets commented on apcd-cms/src/apps/registrations/static/registrations/css/submission_form.css
> +  margin: 0;
```suggestion
```

2023-03-22 20:35 UTC, fnets approved these changes

2023-03-22 20:35 UTC, fnets approved these changes
LGTM! A really simple solution

2023-03-22 21:29 UTC, sophia-massie approved these changes
LGTM!

2023-03-22 21:50 UTC, merged