task/FP-1974/1976: Util function for checking inputs for whitespace only
TACC/Core-CMS-Custom pull request #137
Opened 2023-03-22 20:46 UTC by edmondsgarrett

## Overview
…

## Related

- [FP-1974](https://jira.tacc.utexas.edu/browse/FP-1974)
- [FP-1976](https://jira.tacc.utexas.edu/browse/FP-1976)
…

## Changes
- Added `.js` script for checking an `<input>` for spaces only, and resetting said `<input>`'s value to nothing so the tag's `required` prop can catch it
- Registered `utils` as custom app for above JS script
- Implemented whitespace check on registration form
…

## Testing

1. Load http://localhost:8000/register/request-to-submit/
2. Fill out form as normal, but fill some text-only inputs with spaces, and try to submit form
3. Confirm form does not successfully submit, and instead redirects back to first field filled with spaces & that said field is now blank (ie with <i>no</i> spaces)
4. Continue trying to submit (depending on number of fields you filled with spaces only) to ensure form catches every instance
5. Confirm that, once all required fields are not whitespace, that form submits

## UI

…

2023-03-22 21:03 UTC, sophia-massie requested changes
This is amazing and will be so helpful for all forms on this project. Thank you so much! Only thing is it's missing a catch for the additional contacts and entities on the register to submit form.

2023-03-22 21:03 UTC, sophia-massie commented on apcd-cms/src/apps/utils/static/utils/js/checkForBlankInputs.js
> +formTextInputs.forEach(i => i.addEventListener('change', () => {
Need to add something here that also checks the text fields within the hidden html for entities and contacts when more than one is added. It's letting me submit with blank second inputs in the second contact and second entity.

2023-03-22 22:11 UTC, sophia-massie approved these changes
LGTM and works locally! Thanks for the quick turn around on this it's a huge help!

2023-03-22 22:11 UTC, fnets commented on apcd-cms/src/apps/utils/static/utils/js/checkForBlankInputs.js
Is there a reason this wasn't put into `utils/utils.py`? Then you could clean up a lot of the other files, and also make that file a little more useful.

2023-03-22 22:16 UTC, edmondsgarrett commented on apcd-cms/src/apps/utils/static/utils/js/checkForBlankInputs.js
Oh yeah, well I first created a separate script for this as its JavaScript, and then I placed it where I did so Django would pick it up and I could load it into an HTML template via static

2023-03-23 17:54 UTC, jmartinez-tacc approved these changes
LGTM!

2023-03-23 21:05 UTC, fnets commented on apcd-cms/src/apps/utils/static/utils/js/checkForBlankInputs.js
Duh! Didn't even realize what language I was reading at the end of the day!

2023-03-23 21:17 UTC, fnets approved these changes

2023-03-23 22:00 UTC, merged