Exception list React implementation
TACC/Core-CMS-Custom pull request #329
Opened 2024-10-15 19:54 UTC by jmartinez-tacc

## Overview

Exception list React implementation

## Related

[WP-635](https://tacc-main.atlassian.net/browse/WP-635)

## Changes

Exception list and modals conversion.

## Testing

1. Navigate to http://localhost:8000/administration/list-exceptions/
2. Select filters and make sure those filters are applied to the Exceptions list
3. From Actions drop-down select View Record, make sure the information is displayed
4. From Actions drop-down select Edit Record, make sure the information is updated and changes are reflected on View Record modal window and listing

## UI

<img width="1478" alt="Screenshot 2024-10-15 at 2 52 25 PM" src="https://github.com/user-attachments/assets/939b2837-9cfa-44db-ac4d-1a0059982b82">
<img width="798" alt="Screenshot 2024-10-15 at 2 52 42 PM" src="https://github.com/user-attachments/assets/9bc11d6c-02be-443d-82cd-f0235d1a625b">
<img width="484" alt="Screenshot 2024-10-15 at 2 52 58 PM" src="https://github.com/user-attachments/assets/18dbc52f-bda1-4fc3-804d-342f9b5c46df">
<img width="477" alt="Screenshot 2024-10-15 at 2 53 08 PM" src="https://github.com/user-attachments/assets/5a05c6da-d4d0-48f8-95b2-04d2373eaa85">

2024-10-16 15:34 UTC, chandra-tacc requested changes
The edit modal for exception has differences between localhost and [dev.apcd.](https://dev.apcd.tacc.utexas.edu/administration/list-exceptions/)

There is header and field list is different in dev and production. See below
<img width="759" alt="Screenshot 2024-10-16 at 10 27 53 AM" src="https://github.com/user-attachments/assets/7abe9d9a-3ea5-4ad0-9244-f2d3fc35b3a4">

2024-10-16 19:42 UTC, sophia-massie requested changes
LGTM here are some ideas for styling. May be a good idea as a follow on to eventually factor out global element styles (modal, input, table, etc) so that all table listing, form fields, and modals start with the same basic layout and then have that sheet applied to main.tsx

2024-10-16 19:42 UTC, sophia-massie commented on apcd-cms/src/client/src/components/Admin/EditExceptionModal/EditExceptionModal.module.css
Here are some styles currently being applied to the modal and listing part of the page before your style module (EditExceptionModal.module.css) https://github.com/TACC/Core-CMS-Custom/tree/main/apcd_cms/src/apps/admin_exception/static/admin_exception/css

2024-10-16 19:42 UTC, sophia-massie commented on apcd-cms/src/client/src/components/Admin/ViewExceptionModal/ViewExceptionModal.module.css
Here are some styles currently being applied to the modal that could be conflicting with is. https://github.com/TACC/Core-CMS-Custom/tree/main/apcd_cms/src/apps/admin_exception/static/admin_exception/css

2024-10-16 19:42 UTC, sophia-massie commented on apcd-cms/src/apps/admin_exception/templates/view_admin_exception_modal.html
>  <link rel="stylesheet" href="{% static 'apcd-cms/css/modal.css' %}">
Some of your style modules (ViewExceptionModal.module.css in this case) may be clashing with these stylesheets here and might be why the modals don't look the same as dev/staging/prod.

2024-11-01 15:20 UTC, chandra-tacc approved these changes
approved in current state with known follow up bugs

2024-11-01 15:26 UTC, merged