task/FP-1963: Move actions to dropdown
TACC/Core-CMS-Custom pull request #62
Opened 2023-01-10 21:02 UTC by edmondsgarrett

## Overview
Converted links to action modals in 'Actions' column on admin registrations listing to a dropdown
…

## Related

- [FP-1963](https://jira.tacc.utexas.edu/browse/FP-1963)
…

## Changes
- Removed links from actions column
- Added `select` element containing options corresponding to each action
- Added JSX function to open modal upon clicking in `select`
- Removed old code from table view 
…

## Testing

1. Replace lines 13-15 in `apps/admin_regis_table/views.py` with the following:
   <details><summary>Snippet</summary>
     
          import datetime
          registrations_content = [
            (
                1,                                  #registration_id
                datetime.date(2022, 8, 3),          #posted_date
                12023,                              #applicable_period_start
                122023,                             #applicable_period_end
                True,                               #file_me
                False,                               #file_pv
                True,                               #file_mc
                True,                               #file_pc
                False,                              #file_dc
                True,                               #submitting_for_self
                'SFTP',                             #submission_method
                'received',                           #registration_status
                'insurance carrier',                #org_type
                'Golden Rule Insurance Company',    #business_name
                '7440 Woodland Drive',              #mail_address
                'Indianpolis',                      #city
                'IN',                               #state
                '46278     '                        #zip
            ),
            (
                2,                                  #registration_id
                datetime.date(2022, 8, 3),          #posted_date
                12023,                              #applicable_period_start
                122023,                             #applicable_period_end
                True,                               #file_me
                True,                               #file_pv
                True,                               #file_mc
                True,                               #file_pc
                False,                              #file_dc
                False,                               #submitting_for_self
                'SFTP',                             #submission_method
                'processing',                           #registration_status
                'insurance carrier',                #org_type
                'Clay Tenant Insurance Company',    #business_name
                '440 Wood and Drive',              #mail_address
                'Indianapolis',                      #city
                'NY',                               #state
                '24444     '                        #zip
            ),
            (
                3,                                  #registration_id
                datetime.date(2022, 8, 3),          #posted_date
                12023,                              #applicable_period_start
                122023,                             #applicable_period_end
                True,                               #file_me
                True,                               #file_pv
                True,                               #file_mc
                True,                               #file_pc
                False,                              #file_dc
                True,                               #submitting_for_self
                'SFTP',                             #submission_method
                'complete',                        #registration_status
                'insurance carrier',                #org_type
                'Magenta Condition Insurance Company',    #business_name
                '742 Oddland Drive',              #mail_address
                'Indipolis',                      #city
                'MI',                               #state
                '62784     '                        #zip
            )
        ]
        registrations_entities = [
            (
                5, 1, 5, 46, 11111, 0, 5, 'Garretts Test Business 2', '11-0001111'
            ),
            (
                5, 2, 50000, 47, 1010, 1101, 1, 'A Second Test Entity', '00-0000000'
            )
        ]
        registrations_contacts = [
            (
                52,
                1,
                False,
                'Test Role',
                'Garrett Test Tester',
                '2222222222',
                'notarealemail@emailplace.email'
            ),
            (
                53,
                1,
                False,
                'A 2nd Test Role',
                'Test Garrett 2 Test',
                '145555555555',
                'testemail@testemail.emailtest'
            ),
            (
                54,
                2,
                True,
                'A 3rd and final test role',
                'Test 3rd Role Name Garrett',
                '0000000000',
                None
            )
          ]
        
    </details>
2. Open http://localhost:8000/administration/list-registration-requests/
3. Use any of the dropdowns within the 'Actions' column and test:
    - That when you select any action, the corresponding modal opens
    - The text of the dropdown you used (on the page) still reads 'Select Action'
    - The open modal cannot be closed by clicking outside of the modal
    - Clicking the 'X' button in the header successfully dismisses the modal

## UI
Before:
![image](https://user-images.githubusercontent.com/43251554/211661740-5f71254b-ee44-47bb-bf98-63dddb55b898.png)
After:
![image](https://user-images.githubusercontent.com/43251554/211661851-97cf47d7-16cf-4175-af79-fd6e6622a0f5.png)

…

2023-01-10 21:26 UTC, wesleyboar commented on apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
> +    $(`#${modal_id}`).modal({backdrop: "static"});
<sup>**Reminder for Self**: Element is selected via Bootstrap out of convenience because jQuery is (probably) required for modal interaction.<sup>

2023-01-10 21:27 UTC, wesleyboar approved these changes

2023-01-11 21:44 UTC, fnets requested changes

2023-01-11 21:44 UTC, fnets commented on apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
> +  function openAction(reg_id) {
```suggestion
  function openAction(reg_id, value) {
```

2023-01-11 21:44 UTC, fnets commented on apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
> +    selectedOption = dropdown.options[dropdown.selectedIndex].value;
```suggestion
    selectedOption = value;
```

2023-01-11 21:44 UTC, fnets commented on apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
> +                    <select id='actionsDropdown' class='status-filter' onchange="openAction('{{r.reg_id}}')">
```suggestion
                    <select id='actionsDropdown' class='status-filter' onchange="openAction('{{r.reg_id}}', value)">
```

2023-01-11 21:44 UTC, fnets commented on apcd-cms/src/apps/admin_regis_table/templates/list_registrations.html
> +  function openAction(reg_id) {
This is really slick! But when the modals didn't open on the second and third row of options, it was a little hard for me to debug. I know I'd appreciate it if there was a comment explaining what's going on, or the variable names were a little more unique. It's hard for my brain to figure out the difference between dropdown, selectedOption, and actionsDropdown. Good work, you're getting a lot done here with just a couple lines.

2023-01-11 21:58 UTC, wesleyboar reviewed
I agree. Some polish would let others new to this kind of "raw scripting" follow this easier.

2023-01-20 23:04 UTC, fnets approved these changes
LGTM! Thanks for the comments!

2023-01-23 15:36 UTC, merged