Fp 1815 exception page 1 23
TACC/Core-CMS-Custom pull request #83
Opened 2023-01-31 22:36 UTC by sophia-massie

## Overview

…

## Related

…

## Changes

…

## Testing

1.

## UI

…

2023-02-07 16:49 UTC, fnets requested changes
A couple of fake data assignments made it into the PR. Mind taking those out?

2023-02-07 16:49 UTC, fnets commented on apcd-cms/src/apps/exception/views.py
> +        submitters = [(1, 'TESTGOLD', 10000000, 'thbrown', 'chcd'), (4, 'TESTMRTN', 10000003, 'thbrown', 'chcd')]
```suggestion
```

2023-02-07 16:49 UTC, fnets commented on apcd-cms/src/apps/exception/views.py
> +        submitters = [(1, 'TESTGOLD', 10000000, 'thbrown', 'chcd'), (4, 'TESTMRTN', 10000003, 'thbrown', 'chcd')]
```suggestion
```

2023-02-07 17:45 UTC, sophia-massie reviewed
Changes updated

2023-02-07 23:09 UTC, fnets approved these changes
LGTM and really readable! Good work

2023-02-08 15:42 UTC, edmondsgarrett commented on apcd-cms/src/apps/exception/templates/exception_submission_form/exception_submission_error.html
> +    <a class="c-button c-button--primary" href="/submissions/exceptions/">Go Back to Exception Form</a>
```suggestion
    <a class="c-button c-button--primary" href="/submissions/exception/">Go Back to Exception Form</a>
```
Back button is broken

2023-02-08 15:46 UTC, edmondsgarrett commented on apcd-cms/src/apps/exception/templates/exception_submission_form/exception_form_success.html
> +    <a class="c-button c-button--primary" href="/submissions/exception">Go Back to Exception Form</a>
```suggestion
    <a class="c-button c-button--primary" href="/submissions/exception/">Go Back to Exception Form</a>
```
Back button consistency

2023-02-08 15:47 UTC, edmondsgarrett approved these changes
LGTM!

2023-02-08 15:47 UTC, merged