View users
TACC/Core-CMS-Custom pull request #90
Opened 2023-02-06 19:07 UTC by davidmtacc

## Overview
Added "All" to dropdown list. Made Dropdown list display sorted alphabetically and not show duplicates.
Cleaned up by removing console logs and duplicate code in views.
…

## Related

…

## Changes

Added javascript to sort dropdown list and table.  Changed dropdown list to include ALL

## Testing

1. Tested using made-up data on local machine
2. 
![Screenshot 2023-02-06 at 11 04 42 AM](https://user-images.githubusercontent.com/12832518/217062483-01553fc8-ec0b-4788-b9e9-d76843f07dec.png)

## UI

…

2023-02-07 15:37 UTC, sophia-massie commented on apcd-cms/src/apps/view_users/views.py
Remove import datetime from get_context_data

2023-02-07 15:39 UTC, sophia-massie commented on apcd-cms/src/apps/view_users/views.py
Pass user_content in from main view by passing it in as an argument to the get_context_data function like this:

def get_context_data(self, user_content = user_content, *args, **kwargs):

Then remove line 23

2023-02-07 16:47 UTC, sophia-massie requested changes
Is there a way to change it so the role_id lists whether someone is a Submitter User, Submitter Admin, or APCD Admin instead of a number?

2023-02-07 16:58 UTC, fnets requested changes
Looks like the `utils` function `get_usersIO` is deleted, but still used in the `view_users/views.py`

2023-02-07 20:22 UTC, davidmtacc commented
Updated to make changes requested.

2023-02-08 00:08 UTC, sophia-massie requested changes
Some issues with responsive formatting when making the screen smaller that might affect cell phones. Table column headers become row headers which is fine but then some of the row headers disappear. Maybe responsive design is something to look over on a second pass once all the pieces are working. Everything else looks good after the change is made.

2023-02-08 00:08 UTC, sophia-massie commented on apcd-cms/src/apps/view_users/views.py
> +    def get_context_data(self, user_content, *args, **kwargs):
```suggestion
    def get_context_data(self, user_content=user_content, *args, **kwargs):
```

2023-02-08 16:42 UTC, sophia-massie approved these changes
May need to re-think how the table formats dates and role ID on a second pass. Also columns on right are squished compared to the email column. Everything is working as intended though and we can get with Tracy and UT Health for design direction.

2023-02-08 17:40 UTC, edmondsgarrett approved these changes
LGTM! Agreed with Sophia's notes on UI

2023-02-08 18:35 UTC, fnets requested changes
As far as I can tell, the parts I suggested to delete are no longer used.

2023-02-08 18:35 UTC, fnets commented on apcd-cms/src/apps/view_users/views.py
>              user_view = [usr for usr in user_content if usr[1] == user[0]]
```suggestion
```

2023-02-08 18:35 UTC, fnets commented on apcd-cms/src/apps/view_users/views.py
>          def _set_modal_content(usr):
```suggestion
```

2023-02-08 18:35 UTC, fnets commented on apcd-cms/src/apps/view_users/views.py
>          actions = 'View'
```suggestion
```

2023-02-08 19:36 UTC, fnets approved these changes
LGTM!

2023-02-08 19:48 UTC, merged